name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
     - 'master'
    paths:
     - '**.ts'
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm i
      - run: sed -i '3s/\([0-9]\{1,3\}\.[0-9]\{1,3\}\)\.[0-9]\{1,3\}/\1.${{ github.run_number }}/g' package.json
      - run: npm run build
      - run: npm publish
